### ISSUE TITLE
vendor/autoload.php

### ISSUE THREAD

**Issue by AlphaDG** [donatj/SimpleCalendar#17]
There is no 'vendor' folder, so there is no 'autoload.php' file. There is no 'autoload.php' file located anywhere in this project.

**Comment by donatj** [comment]
I'm guessing you're relatively new to the PHP ecosystem?

`vendor/autoload.php` is a file automatically generated by the Composer package manager.

Composer isn't required to use the Calendar, you can instead just require `src/SimpleCalendar.php` 

That said, composer is a powerful tool for managing your dependencies and basically everything in the PHP ecosystem these days depends on it. [Here is decent little getting started](https://www.codementor.io/@jadjoubran/php-tutorial-getting-started-with-composer-8sbn6fb6t) guide to get you started.

**Comment by AlphaDG** [comment]
I appreciate the details. I have never heard of the PHP 'ecosystem', but I have been writing in PHP for about 10 years, along with 6 other languages. I have never used Composer, or any 'framework'. I open notepad and write the code. :)

**Comment by AlphaDG** [comment]
'EDIT' would be nice on Github! Due to my poor wording, I would like to add that I have been writing code since long before Windows existed (about 40 years ago) :)
