### ISSUE TITLE
Translating the names of the month

### ISSUE THREAD

**Issue by tellustheguru** [donatj/SimpleCalendar#24]
I wonder if there is a possibility to name the months in the same way as the days of the week, so if you scroll between the months, this is displayed in my case in Swedish...

like:

  $calendar->setMonthNames(['januari', 'februari, 'mars', 'april', 'maj', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'december']);

**Comment by donatj** [comment]
The calendar listing doesn't include the month name anywhere in it's output. 

That's left up to you to implement, all this does is list the days in a calendar layout. 

<img width="649" alt="image" src="https://github.com/donatj/SimpleCalendar/assets/133747/39e46fca-3753-4a16-b312-eab33413e3a9">
