### ISSUE TITLE
No 2weekly option 

### ISSUE THREAD

**Issue by dunfy** [donatj/SimpleCalendar#8]
Can you add 2weekly or explain how it's possible to generate events every 2 weeks. 

Cheers.

**Comment by donatj** [comment]
Are you talking about displaying just two weeks, something like?

![screen shot 2017-04-21 at 5 47 08 pm](https://cloud.githubusercontent.com/assets/133747/25298462/9ab15c42-26ba-11e7-8fe8-ca720c6d9b30.png)

No function for that currently exists, but it would be an interesting addition.  I'll ponder if I can do that in a way that doesn't overcomplicate the class.

**Comment by dunfy** [comment]
No. I'm talking about events that occur every 2 weeks. 

For example, The event will start on 1st April, then won't reoccur until again until the 15 April, then again on 29th April. 

I've put in a really hacky fix for the moment that uses the weekly occurrence and skips a week, but it would be nice if your library supports bi-weekly. 

Cheers. 

Dan

**Comment by dunfy** [comment]
My bad, I was looking at the wrong repo :)

**Comment by donatj** [comment]
Lol different calendar class I presume?
